#!/bin/bash
# BGP Policy Verification Script

echo "=========================================="
echo "BGP Traffic Engineering Policy Verification"
echo "=========================================="
echo ""

echo "1. Checking BGP sessions on R2 (ISP #1)..."
echo "-------------------------------------------"
echo "R2 should have:"
echo "  - Peering with R7 (10.0.9.2) - AS 300"
echo "  - Transit with R4 (10.0.3.2) - AS 100"
echo ""
sudo python3 -c "
from mininet.net import Mininet
from mininet.cli import CLI
import sys
# This is a placeholder - run manually in Mininet CLI
print('Run in Mininet CLI:')
print('  r2 vtysh -c \"show ip bgp summary\"')
"

echo ""
echo "2. Checking BGP routes on R2..."
echo "-------------------------------------------"
echo "Routes from ISP #2 (192.168.3.0/24, 192.168.4.0/24) should show:"
echo "  - Via R7 (peering): Local Pref = 200 (BEST PATH)"
echo "  - Via R4 (transit): Local Pref = 100 (backup)"
echo ""
echo "Run in Mininet CLI:"
echo "  r2 vtysh -c \"show ip bgp 192.168.4.0/24\""
echo ""

echo "3. Checking BGP sessions on R7 (ISP #2)..."
echo "-------------------------------------------"
echo "R7 should have:"
echo "  - Peering with R2 (10.0.9.1) - AS 200"
echo "  - Transit with R6 (10.0.6.1) - AS 100"
echo ""
echo "Run in Mininet CLI:"
echo "  r7 vtysh -c \"show ip bgp summary\""
echo ""

echo "4. Checking BGP routes on R7..."
echo "-------------------------------------------"
echo "Routes from ISP #1 (192.168.1.0/24, 192.168.2.0/24) should show:"
echo "  - Via R2 (peering): Local Pref = 200 (BEST PATH)"
echo "  - Via R6 (transit): Local Pref = 100 (backup)"
echo ""
echo "Run in Mininet CLI:"
echo "  r7 vtysh -c \"show ip bgp 192.168.1.0/24\""
echo ""

echo "5. Testing actual traffic path..."
echo "-------------------------------------------"
echo "Traffic between ISP #1 and ISP #2 should use peering link"
echo ""
echo "Run in Mininet CLI:"
echo "  pc1 traceroute -n 192.168.4.2"
echo ""
echo "Expected path (via peering):"
echo "  192.168.1.2 → 192.168.1.1 (R1) → 10.0.1.2 (R2) → 10.0.9.2 (R7) → ... → 192.168.4.2"
echo ""
echo "NOT via transit:"
echo "  192.168.1.2 → ... → R2 → R4 → R5 → R6 → R7 → ... → 192.168.4.2"
echo ""

echo "=========================================="
echo "Manual Verification Commands"
echo "=========================================="
echo ""
echo "In Mininet CLI, run these commands:"
echo ""
echo "# Check R2 BGP table"
echo "r2 vtysh -c 'show ip bgp'"
echo ""
echo "# Check R2 routes with details (look for Local Pref)"
echo "r2 vtysh -c 'show ip bgp 192.168.4.0/24'"
echo ""
echo "# Check R7 BGP table"
echo "r7 vtysh -c 'show ip bgp'"
echo ""
echo "# Check R7 routes with details"
echo "r7 vtysh -c 'show ip bgp 192.168.1.0/24'"
echo ""
echo "# Test connectivity and path"
echo "pc1 ping -c 3 192.168.4.2"
echo "pc1 traceroute -n 192.168.4.2"
echo ""
echo "# Check route-maps are applied"
echo "r2 vtysh -c 'show ip bgp neighbors 10.0.9.2'"
echo "r2 vtysh -c 'show ip bgp neighbors 10.0.3.2'"
echo ""

echo "=========================================="
echo "Expected Results"
echo "=========================================="
echo ""
echo "✓ BGP sessions: All should be 'Established'"
echo "✓ Local Preference: Peering routes = 200, Transit routes = 100"
echo "✓ Best path: Routes via peering should be marked with '>'"
echo "✓ Traceroute: Should show direct path R2 → R7, not via Tier 1"
echo ""
